### ISSUE TITLE
The white words are too bright.

### ISSUE THREAD

**Issue by binlidaily** [StylishThemes/Quora-Dark#11] opened 2017-02-03 04:49 UTC
The words are more soft as shown in _Quora - Solarized Dark_. Is it possible to turn down the bright of the words?

**Comment by Mottie** [comment] 2017-02-03 11:23
Hi @leebeanstriving!

To which text color are you referring?

* Most text is set to use `#ddd`.
* Action buttons have text set to `#eee`.
* Text selection has the text color set to `#fff`.

**Comment by binlidaily** [comment] 2017-02-03 14:04
I think the most text color is a little bit bright. 

Besides, the background of popup window is white?

![image](https://cloud.githubusercontent.com/assets/5987437/22594058/6f1e5fa2-ea5c-11e6-871a-dd5e067e29a5.png)

**Comment by Mottie** [comment] 2017-02-03 15:42
The popup should already be dark... try updating your style directly from https://userstyles.org/styles/104706 - there have been some issues with Chrome not updating the userstyle... and one way to make sure the style is up-to-date is to update it directly.

**Comment by binlidaily** [comment] 2017-02-04 02:38
I check it just now, the popup is dark. Thank you so much.

**Comment by Mottie** [comment] 2017-02-04 03:43
And the text? Is it still too bright?

**Comment by binlidaily** [comment] 2017-02-04 03:49
It is bright for me. You can compare the two dark theme as shown in the pic.

Quora vs Github

![image](https://cloud.githubusercontent.com/assets/5987437/22615431/ab1de446-eacf-11e6-91be-cad69326a4b7.png)

**Comment by Mottie** [comment] 2017-02-04 18:32
Ok, I've reduced the white intensity to match GitHub-Dark. Let me know what you think!

**Comment by binlidaily** [comment] 2017-02-07 05:32
Maybe it's my problem. I still feel it is bright.

**Comment by binlidaily** [comment] 2017-02-07 05:34
Can I customize font in my browser?

**Comment by binlidaily** [comment] 2017-02-07 05:44
![1486445939](https://cloud.githubusercontent.com/assets/5987437/22679156/e7d96a3c-ed3a-11e6-86ae-e198ebb2549d.jpg)

wikipedia vs quora

It's better compared to previous version for me. Maybe it's my own preference, I like text color in wikipedia. The current version is fine. Thank you very much.

**Comment by Mottie** [comment] 2017-02-08 21:27
Yeah, the wikipedia style is using `#9a9a9a` as the overall text color. I'll try it on Quora and see if making it even darker works out.

The Quora style doesn't modify the font at all. But with Stylish (or better yet, Stylus) you can add a custom userstyle to modify the font.

**Comment by binlidaily** [comment] 2017-02-13 03:11
After updating, the ponup becomes white again.

![image](https://cloud.githubusercontent.com/assets/5987437/22869818/f7798606-f1dc-11e6-804d-2eb52e549f45.png)

**Comment by Mottie** [comment] 2017-02-13 17:51
I can't reproduce this issue. Maybe try to uninstall then re-install the style.

**Comment by Mottie** [comment] 2017-05-31 19:09
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Closed as completed by Mottie** 2017-05-31 19:09 UTC
Labels: enhancement :100:
